name = "alfin-ai-id"
account_id = "b534acd3a8238a6391b64da112d23eaf"
compatibility_date = "2025-10-01"
main = "src/worker.js"

[vars]
AUTOPAY_BASE_URL = "https://autopay.web.id"

routes = [
  { pattern = "alfin.ai.id", custom_domain = true },
  { pattern = "www.alfin.ai.id", custom_domain = true },
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"

[[d1_databases]]
binding = "DB"
database_name = "alfin-store"
database_id = "9bf38569-44c2-4387-9b84-4abb97fce7dd"
